datasource:
  url: 'jdbc:postgresql://localhost:35100/tink'
  username: 'user'
  password: 'password'
helios:
  datasource:
    url: jdbc:postgresql://pg:5432/studs
    username: s336805
    password: 4lyZcxbHImiBFZxr
  local-storage:
    location: /home/studs/s336805/files
jpa:
  dialect: org.hibernate.dialect.PostgreSQLDialect
liquibase:
  change-log: classpath:/db/changelog/main-changelog.yaml
swagger-setup:
  swagger-path: /moi-swagger.html
file:
  max-size: 5MB
quartz:
  driver: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
jwt-token:
  secret: 77397A24432646294A404E635266556A586E3272357538782F4125442A472D4B
  issuer: daniil
local-storage:
  location: /home/kalin/IdeaProjects/tinkoff-project-develop/files
front-url: http://localhost:8080
admin-data:
  email: admin@admin.ru
  nickname: admin
  password: admin